name = "XLSX"
uuid = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
license = "MIT"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
repo = "https://github.com/felipenoris/XLSX.jl.git"
version = "0.10.5-dev"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"
ZipArchives = "49080126-0e18-4c2a-b176-c102e4b3760c"

[compat]
Tables = "1"
XML = "0.3.5"
ZipArchives = "2"
julia = "1.7"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames"]
