name = "XLSX"
uuid = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
license = "MIT"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
repo = "https://github.com/felipenoris/XLSX.jl.git"
version = "0.5.4"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
